//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.27 at 10:14:55 PM PDT 
//


package nebulous.conquest.logic;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateAmmoSourceKey_QNAME = new QName("", "AmmoSourceKey");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStatePartialFiring_QNAME = new QName("", "PartialFiring");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateMissiles_QNAME = new QName("", "Missiles");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateCycleTimeElapsed_QNAME = new QName("", "CycleTimeElapsed");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateMags_QNAME = new QName("", "Mags");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateNextDebuffID_QNAME = new QName("", "NextDebuffID");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateFiredCount_QNAME = new QName("", "FiredCount");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateTurretState_QNAME = new QName("", "TurretState");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateRestoresConsumed_QNAME = new QName("", "RestoresConsumed");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateWaitingForCooldown_QNAME = new QName("", "WaitingForCooldown");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateWaitingForMuzzle_QNAME = new QName("", "WaitingForMuzzle");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateFiringAccum_QNAME = new QName("", "FiringAccum");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateCellAccum_QNAME = new QName("", "CellAccum");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateReloading_QNAME = new QName("", "Reloading");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateMuzzleAccum_QNAME = new QName("", "MuzzleAccum");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateCycleActive_QNAME = new QName("", "CycleActive");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateReloadAccum_QNAME = new QName("", "ReloadAccum");
    private final static QName _FleetShipsShipSocketMapHullSocketComponentStateCooldownAccum_QNAME = new QName("", "CooldownAccum");
    private final static QName _FleetShipsShipSavedStateOrdersSavedOrderTaskDogleg_QNAME = new QName("", "Dogleg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SerializedFleet }
     * 
     */
    public SerializedFleet createFleet() {
        return new SerializedFleet();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes }
     * 
     */
    public SerializedFleet.MissileTypes createFleetMissileTypes() {
        return new SerializedFleet.MissileTypes();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate createFleetMissileTypesMissileTemplate() {
        return new SerializedFleet.MissileTypes.MissileTemplate();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.Sockets }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.Sockets createFleetMissileTypesMissileTemplateSockets() {
        return new SerializedFleet.MissileTypes.MissileTemplate.Sockets();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket createFleetMissileTypesMissileTemplateSocketsMissileSocket() {
        return new SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent createFleetMissileTypesMissileTemplateSocketsMissileSocketInstalledComponent() {
        return new SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships }
     * 
     */
    public SerializedFleet.Ships createFleetShips() {
        return new SerializedFleet.Ships();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship }
     * 
     */
    public SerializedFleet.Ships.Ship createFleetShipsShip() {
        return new SerializedFleet.Ships.Ship();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState createFleetShipsShipSavedState() {
        return new SerializedFleet.Ships.Ship.SavedState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents createFleetShipsShipSavedStateBulkComponents() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState createFleetShipsShipSavedStateBulkComponentsComponentState() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy createFleetShipsShipSavedStateBulkComponentsComponentStateTrackedBy() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record createFleetShipsShipSavedStateBulkComponentsComponentStateTrackedByRecord() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Orders }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Orders createFleetShipsShipSavedStateOrders() {
        return new SerializedFleet.Ships.Ship.SavedState.Orders();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask createFleetShipsShipSavedStateOrdersSavedOrderTask() {
        return new SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets createFleetShipsShipSavedStateOrdersSavedOrderTaskTargets() {
        return new SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.NavOrder }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.NavOrder createFleetShipsShipSavedStateNavOrder() {
        return new SerializedFleet.Ships.Ship.SavedState.NavOrder();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.NavOrder.Path }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.NavOrder.Path createFleetShipsShipSavedStateNavOrderPath() {
        return new SerializedFleet.Ships.Ship.SavedState.NavOrder.Path();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.PDState }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.PDState createFleetShipsShipSavedStatePDState() {
        return new SerializedFleet.Ships.Ship.SavedState.PDState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.CrewState }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.CrewState createFleetShipsShipSavedStateCrewState() {
        return new SerializedFleet.Ships.Ship.SavedState.CrewState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves createFleetShipsShipSavedStateCrewStateReserves() {
        return new SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments createFleetShipsShipSavedStateCrewStateAssignments() {
        return new SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Damage }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Damage createFleetShipsShipSavedStateDamage() {
        return new SerializedFleet.Ships.Ship.SavedState.Damage();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Damage.Armor }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Damage.Armor createFleetShipsShipSavedStateDamageArmor() {
        return new SerializedFleet.Ships.Ship.SavedState.Damage.Armor();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Damage.Parts }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Damage.Parts createFleetShipsShipSavedStateDamageParts() {
        return new SerializedFleet.Ships.Ship.SavedState.Damage.Parts();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Rotation }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Rotation createFleetShipsShipSavedStateRotation() {
        return new SerializedFleet.Ships.Ship.SavedState.Rotation();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.WeaponGroups }
     * 
     */
    public SerializedFleet.Ships.Ship.WeaponGroups createFleetShipsShipWeaponGroups() {
        return new SerializedFleet.Ships.Ship.WeaponGroups();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.WeaponGroups.WepGroup }
     * 
     */
    public SerializedFleet.Ships.Ship.WeaponGroups.WepGroup createFleetShipsShipWeaponGroupsWepGroup() {
        return new SerializedFleet.Ships.Ship.WeaponGroups.WepGroup();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap createFleetShipsShipSocketMap() {
        return new SerializedFleet.Ships.Ship.SocketMap();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket createFleetShipsShipSocketMapHullSocket() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState createFleetShipsShipSocketMapHullSocketComponentState() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags createFleetShipsShipSocketMapHullSocketComponentStateMags() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles createFleetShipsShipSocketMapHullSocketComponentStateMissiles() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData createFleetShipsShipSocketMapHullSocketComponentData() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load createFleetShipsShipSocketMapHullSocketComponentDataLoad() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad createFleetShipsShipSocketMapHullSocketComponentDataMissileLoad() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.BaseColor }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.BaseColor createFleetMissileTypesMissileTemplateBaseColor() {
        return new SerializedFleet.MissileTypes.MissileTemplate.BaseColor();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.StripeColor }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.StripeColor createFleetMissileTypesMissileTemplateStripeColor() {
        return new SerializedFleet.MissileTypes.MissileTemplate.StripeColor();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.DefensiveDoctrine }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.DefensiveDoctrine createFleetMissileTypesMissileTemplateSocketsMissileSocketInstalledComponentDefensiveDoctrine() {
        return new SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.DefensiveDoctrine();
    }

    /**
     * Create an instance of {@link SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.BalanceValues }
     * 
     */
    public SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.BalanceValues createFleetMissileTypesMissileTemplateSocketsMissileSocketInstalledComponentBalanceValues() {
        return new SerializedFleet.MissileTypes.MissileTemplate.Sockets.MissileSocket.InstalledComponent.BalanceValues();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Position }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Position createFleetShipsShipSavedStatePosition() {
        return new SerializedFleet.Ships.Ship.SavedState.Position();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.LinearVel }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.LinearVel createFleetShipsShipSavedStateLinearVel() {
        return new SerializedFleet.Ships.Ship.SavedState.LinearVel();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.AngularVel }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.AngularVel createFleetShipsShipSavedStateAngularVel() {
        return new SerializedFleet.Ships.Ship.SavedState.AngularVel();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.ID }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.ID createFleetShipsShipSavedStateBulkComponentsComponentStateTrackedByRecordID() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.ID();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.LostContactPosition }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.LostContactPosition createFleetShipsShipSavedStateBulkComponentsComponentStateTrackedByRecordLostContactPosition() {
        return new SerializedFleet.Ships.Ship.SavedState.BulkComponents.ComponentState.TrackedBy.Record.LostContactPosition();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Target }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Target createFleetShipsShipSavedStateOrdersSavedOrderTaskTarget() {
        return new SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Target();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets.TrackIdentifier }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets.TrackIdentifier createFleetShipsShipSavedStateOrdersSavedOrderTaskTargetsTrackIdentifier() {
        return new SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.Targets.TrackIdentifier();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.NavOrder.TruePos }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.NavOrder.TruePos createFleetShipsShipSavedStateNavOrderTruePos() {
        return new SerializedFleet.Ships.Ship.SavedState.NavOrder.TruePos();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.NavOrder.RelativePos }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.NavOrder.RelativePos createFleetShipsShipSavedStateNavOrderRelativePos() {
        return new SerializedFleet.Ships.Ship.SavedState.NavOrder.RelativePos();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.NavOrder.Path.Vector3 }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.NavOrder.Path.Vector3 createFleetShipsShipSavedStateNavOrderPathVector3() {
        return new SerializedFleet.Ships.Ship.SavedState.NavOrder.Path.Vector3();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.PDState.PDSettings }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.PDState.PDSettings createFleetShipsShipSavedStatePDStatePDSettings() {
        return new SerializedFleet.Ships.Ship.SavedState.PDState.PDSettings();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves.Assignment }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves.Assignment createFleetShipsShipSavedStateCrewStateReservesAssignment() {
        return new SerializedFleet.Ships.Ship.SavedState.CrewState.Reserves.Assignment();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments.Assignment }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments.Assignment createFleetShipsShipSavedStateCrewStateAssignmentsAssignment() {
        return new SerializedFleet.Ships.Ship.SavedState.CrewState.Assignments.Assignment();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Damage.Armor.ArmorSection }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Damage.Armor.ArmorSection createFleetShipsShipSavedStateDamageArmorArmorSection() {
        return new SerializedFleet.Ships.Ship.SavedState.Damage.Armor.ArmorSection();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Damage.Parts.SerializedPartDamage }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Damage.Parts.SerializedPartDamage createFleetShipsShipSavedStateDamagePartsSerializedPartDamage() {
        return new SerializedFleet.Ships.Ship.SavedState.Damage.Parts.SerializedPartDamage();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SavedState.Rotation.EulerAngles }
     * 
     */
    public SerializedFleet.Ships.Ship.SavedState.Rotation.EulerAngles createFleetShipsShipSavedStateRotationEulerAngles() {
        return new SerializedFleet.Ships.Ship.SavedState.Rotation.EulerAngles();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.WeaponGroups.WepGroup.MemberKeys }
     * 
     */
    public SerializedFleet.Ships.Ship.WeaponGroups.WepGroup.MemberKeys createFleetShipsShipWeaponGroupsWepGroupMemberKeys() {
        return new SerializedFleet.Ships.Ship.WeaponGroups.WepGroup.MemberKeys();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState createFleetShipsShipSocketMapHullSocketComponentStateTurretState() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags.MagStateData }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags.MagStateData createFleetShipsShipSocketMapHullSocketComponentStateMagsMagStateData() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags.MagStateData();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles.MagStateData }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles.MagStateData createFleetShipsShipSocketMapHullSocketComponentStateMissilesMagStateData() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles.MagStateData();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.ConfiguredSize }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.ConfiguredSize createFleetShipsShipSocketMapHullSocketComponentDataConfiguredSize() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.ConfiguredSize();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load.MagSaveData }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load.MagSaveData createFleetShipsShipSocketMapHullSocketComponentDataLoadMagSaveData() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.Load.MagSaveData();
    }

    /**
     * Create an instance of {@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData }
     * 
     */
    public SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData createFleetShipsShipSocketMapHullSocketComponentDataMissileLoadMagSaveData() {
        return new SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmmoSourceKey", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStateAmmoSourceKey(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStateAmmoSourceKey_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartialFiring", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStatePartialFiring(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStatePartialFiring_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Missiles", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles> createFleetShipsShipSocketMapHullSocketComponentStateMissiles(SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles value) {
        return new JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles>(_FleetShipsShipSocketMapHullSocketComponentStateMissiles_QNAME, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Missiles.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CycleTimeElapsed", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Float> createFleetShipsShipSocketMapHullSocketComponentStateCycleTimeElapsed(Float value) {
        return new JAXBElement<Float>(_FleetShipsShipSocketMapHullSocketComponentStateCycleTimeElapsed_QNAME, Float.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mags", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags> createFleetShipsShipSocketMapHullSocketComponentStateMags(SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags value) {
        return new JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags>(_FleetShipsShipSocketMapHullSocketComponentStateMags_QNAME, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.Mags.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NextDebuffID", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Byte> createFleetShipsShipSocketMapHullSocketComponentStateNextDebuffID(Byte value) {
        return new JAXBElement<Byte>(_FleetShipsShipSocketMapHullSocketComponentStateNextDebuffID_QNAME, Byte.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FiredCount", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Byte> createFleetShipsShipSocketMapHullSocketComponentStateFiredCount(Byte value) {
        return new JAXBElement<Byte>(_FleetShipsShipSocketMapHullSocketComponentStateFiredCount_QNAME, Byte.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TurretState", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState> createFleetShipsShipSocketMapHullSocketComponentStateTurretState(SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState value) {
        return new JAXBElement<SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState>(_FleetShipsShipSocketMapHullSocketComponentStateTurretState_QNAME, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.TurretState.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RestoresConsumed", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Byte> createFleetShipsShipSocketMapHullSocketComponentStateRestoresConsumed(Byte value) {
        return new JAXBElement<Byte>(_FleetShipsShipSocketMapHullSocketComponentStateRestoresConsumed_QNAME, Byte.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaitingForCooldown", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStateWaitingForCooldown(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStateWaitingForCooldown_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaitingForMuzzle", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStateWaitingForMuzzle(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStateWaitingForMuzzle_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FiringAccum", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Float> createFleetShipsShipSocketMapHullSocketComponentStateFiringAccum(Float value) {
        return new JAXBElement<Float>(_FleetShipsShipSocketMapHullSocketComponentStateFiringAccum_QNAME, Float.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CellAccum", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Float> createFleetShipsShipSocketMapHullSocketComponentStateCellAccum(Float value) {
        return new JAXBElement<Float>(_FleetShipsShipSocketMapHullSocketComponentStateCellAccum_QNAME, Float.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reloading", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStateReloading(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStateReloading_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MuzzleAccum", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Byte> createFleetShipsShipSocketMapHullSocketComponentStateMuzzleAccum(Byte value) {
        return new JAXBElement<Byte>(_FleetShipsShipSocketMapHullSocketComponentStateMuzzleAccum_QNAME, Byte.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CycleActive", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<String> createFleetShipsShipSocketMapHullSocketComponentStateCycleActive(String value) {
        return new JAXBElement<String>(_FleetShipsShipSocketMapHullSocketComponentStateCycleActive_QNAME, String.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReloadAccum", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Float> createFleetShipsShipSocketMapHullSocketComponentStateReloadAccum(Float value) {
        return new JAXBElement<Float>(_FleetShipsShipSocketMapHullSocketComponentStateReloadAccum_QNAME, Float.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CooldownAccum", scope = SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class)
    public JAXBElement<Byte> createFleetShipsShipSocketMapHullSocketComponentStateCooldownAccum(Byte value) {
        return new JAXBElement<Byte>(_FleetShipsShipSocketMapHullSocketComponentStateCooldownAccum_QNAME, Byte.class, SerializedFleet.Ships.Ship.SocketMap.HullSocket.ComponentState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dogleg", scope = SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.class)
    public JAXBElement<String> createFleetShipsShipSavedStateOrdersSavedOrderTaskDogleg(String value) {
        return new JAXBElement<String>(_FleetShipsShipSavedStateOrdersSavedOrderTaskDogleg_QNAME, String.class, SerializedFleet.Ships.Ship.SavedState.Orders.SavedOrderTask.class, value);
    }

}
