//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.08.26 at 12:49:31 PM PDT
//

package nebulous.conquest.logic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SaveID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Callsign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SymbolOption" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="HullType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModDependencies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="unsignedLong" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SocketMap">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HullSocket" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ComponentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ComponentData" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MissileLoad" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="ConfiguredSize" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Load" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WeaponGroups">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="WepGroup">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MemberKeys">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "saveID",
        "key",
        "name",
        "cost",
        "callsign",
        "number",
        "symbolOption",
        "hullType",
        "modDependencies",
        "socketMap",
        "weaponGroups"
})
@XmlRootElement(name = "Ship")
public class SerializedShip {

    @XmlElement(name = "SaveID", required = true, nillable = true)
    protected String saveID;
    @XmlElement(name = "Key", required = true)
    protected String key;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Cost")
    protected short cost;
    @XmlElement(name = "Callsign", required = true)
    protected String callsign;
    @XmlElement(name = "Number")
    protected byte number;
    @XmlElement(name = "SymbolOption")
    protected byte symbolOption;
    @XmlElement(name = "HullType", required = true)
    protected String hullType;
    @XmlElement(name = "ModDependencies", required = true)
    protected SerializedShip.ModDependencies modDependencies;
    @XmlElement(name = "SocketMap", required = true)
    protected SerializedShip.SocketMap socketMap;
    @XmlElement(name = "WeaponGroups", required = true)
    protected SerializedShip.WeaponGroups weaponGroups;

    /**
     * Gets the value of the saveID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSaveID() {
        return saveID;
    }

    /**
     * Sets the value of the saveID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSaveID(String value) {
        this.saveID = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cost property.
     *
     */
    public short getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     *
     */
    public void setCost(short value) {
        this.cost = value;
    }

    /**
     * Gets the value of the callsign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCallsign() {
        return callsign;
    }

    /**
     * Sets the value of the callsign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCallsign(String value) {
        this.callsign = value;
    }

    /**
     * Gets the value of the number property.
     *
     */
    public byte getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     */
    public void setNumber(byte value) {
        this.number = value;
    }

    /**
     * Gets the value of the symbolOption property.
     *
     */
    public byte getSymbolOption() {
        return symbolOption;
    }

    /**
     * Sets the value of the symbolOption property.
     *
     */
    public void setSymbolOption(byte value) {
        this.symbolOption = value;
    }

    /**
     * Gets the value of the hullType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHullType() {
        return hullType;
    }

    /**
     * Sets the value of the hullType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHullType(String value) {
        this.hullType = value;
    }

    /**
     * Gets the value of the modDependencies property.
     *
     * @return
     *     possible object is
     *     {@link SerializedShip.ModDependencies }
     *
     */
    public SerializedShip.ModDependencies getModDependencies() {
        return modDependencies;
    }

    /**
     * Sets the value of the modDependencies property.
     *
     * @param value
     *     allowed object is
     *     {@link SerializedShip.ModDependencies }
     *
     */
    public void setModDependencies(SerializedShip.ModDependencies value) {
        this.modDependencies = value;
    }

    /**
     * Gets the value of the socketMap property.
     *
     * @return
     *     possible object is
     *     {@link SerializedShip.SocketMap }
     *
     */
    public SerializedShip.SocketMap getSocketMap() {
        return socketMap;
    }

    /**
     * Sets the value of the socketMap property.
     *
     * @param value
     *     allowed object is
     *     {@link SerializedShip.SocketMap }
     *
     */
    public void setSocketMap(SerializedShip.SocketMap value) {
        this.socketMap = value;
    }

    /**
     * Gets the value of the weaponGroups property.
     *
     * @return
     *     possible object is
     *     {@link SerializedShip.WeaponGroups }
     *
     */
    public SerializedShip.WeaponGroups getWeaponGroups() {
        return weaponGroups;
    }

    /**
     * Sets the value of the weaponGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link SerializedShip.WeaponGroups }
     *
     */
    public void setWeaponGroups(SerializedShip.WeaponGroups value) {
        this.weaponGroups = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="unsignedLong" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "unsignedLong"
    })
    public static class ModDependencies {

        @XmlElement(type = Long.class)
        protected List<Long> unsignedLong;

        /**
         * Gets the value of the unsignedLong property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unsignedLong property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnsignedLong().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         *
         *
         */
        public List<Long> getUnsignedLong() {
            if (unsignedLong == null) {
                unsignedLong = new ArrayList<Long>();
            }
            return this.unsignedLong;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HullSocket" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ComponentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ComponentData" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="MissileLoad" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="ConfiguredSize" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Load" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "hullSocket"
    })
    public static class SocketMap {

        @XmlElement(name = "HullSocket")
        protected List<SerializedShip.SocketMap.HullSocket> hullSocket;

        /**
         * Gets the value of the hullSocket property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hullSocket property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHullSocket().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SerializedShip.SocketMap.HullSocket }
         *
         *
         */
        public List<SerializedShip.SocketMap.HullSocket> getHullSocket() {
            if (hullSocket == null) {
                hullSocket = new ArrayList<SerializedShip.SocketMap.HullSocket>();
            }
            return this.hullSocket;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ComponentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ComponentData" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="MissileLoad" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="ConfiguredSize" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Load" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "key",
                "componentName",
                "componentData"
        })
        public static class HullSocket {

            @XmlElement(name = "Key", required = true)
            protected String key;
            @XmlElement(name = "ComponentName", required = true)
            protected String componentName;
            @XmlElement(name = "ComponentData")
            protected SerializedShip.SocketMap.HullSocket.ComponentData componentData;

            /**
             * Gets the value of the key property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the componentName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getComponentName() {
                return componentName;
            }

            /**
             * Sets the value of the componentName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setComponentName(String value) {
                this.componentName = value;
            }

            /**
             * Gets the value of the componentData property.
             *
             * @return
             *     possible object is
             *     {@link SerializedShip.SocketMap.HullSocket.ComponentData }
             *
             */
            public SerializedShip.SocketMap.HullSocket.ComponentData getComponentData() {
                return componentData;
            }

            /**
             * Sets the value of the componentData property.
             *
             * @param value
             *     allowed object is
             *     {@link SerializedShip.SocketMap.HullSocket.ComponentData }
             *
             */
            public void setComponentData(SerializedShip.SocketMap.HullSocket.ComponentData value) {
                this.componentData = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="MissileLoad" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="ConfiguredSize" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Load" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "missileLoad",
                    "configuredSize",
                    "load"
            })
            public static class ComponentData {

                @XmlElement(name = "MissileLoad")
                protected SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad missileLoad;
                @XmlElement(name = "ConfiguredSize")
                protected SerializedShip.SocketMap.HullSocket.ComponentData.ConfiguredSize configuredSize;
                @XmlElement(name = "Load")
                protected SerializedShip.SocketMap.HullSocket.ComponentData.Load load;

                /**
                 * Gets the value of the missileLoad property.
                 *
                 * @return
                 *     possible object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad }
                 *
                 */
                public SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad getMissileLoad() {
                    return missileLoad;
                }

                /**
                 * Sets the value of the missileLoad property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad }
                 *
                 */
                public void setMissileLoad(SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad value) {
                    this.missileLoad = value;
                }

                /**
                 * Gets the value of the configuredSize property.
                 *
                 * @return
                 *     possible object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.ConfiguredSize }
                 *
                 */
                public SerializedShip.SocketMap.HullSocket.ComponentData.ConfiguredSize getConfiguredSize() {
                    return configuredSize;
                }

                /**
                 * Sets the value of the configuredSize property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.ConfiguredSize }
                 *
                 */
                public void setConfiguredSize(SerializedShip.SocketMap.HullSocket.ComponentData.ConfiguredSize value) {
                    this.configuredSize = value;
                }

                /**
                 * Gets the value of the load property.
                 *
                 * @return
                 *     possible object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.Load }
                 *
                 */
                public SerializedShip.SocketMap.HullSocket.ComponentData.Load getLoad() {
                    return load;
                }

                /**
                 * Sets the value of the load property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link SerializedShip.SocketMap.HullSocket.ComponentData.Load }
                 *
                 */
                public void setLoad(SerializedShip.SocketMap.HullSocket.ComponentData.Load value) {
                    this.load = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "x",
                        "y"
                })
                public static class ConfiguredSize {

                    protected byte x;
                    protected byte y;

                    /**
                     * Gets the value of the x property.
                     *
                     */
                    public byte getX() {
                        return x;
                    }

                    /**
                     * Sets the value of the x property.
                     *
                     */
                    public void setX(byte value) {
                        this.x = value;
                    }

                    /**
                     * Gets the value of the y property.
                     *
                     */
                    public byte getY() {
                        return y;
                    }

                    /**
                     * Sets the value of the y property.
                     *
                     */
                    public void setY(byte value) {
                        this.y = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "magSaveData"
                })
                public static class Load {

                    @XmlElement(name = "MagSaveData")
                    protected List<SerializedShip.SocketMap.HullSocket.ComponentData.Load.MagSaveData> magSaveData;

                    /**
                     * Gets the value of the magSaveData property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the magSaveData property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getMagSaveData().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link SerializedShip.SocketMap.HullSocket.ComponentData.Load.MagSaveData }
                     *
                     *
                     */
                    public List<SerializedShip.SocketMap.HullSocket.ComponentData.Load.MagSaveData> getMagSaveData() {
                        if (magSaveData == null) {
                            magSaveData = new ArrayList<SerializedShip.SocketMap.HullSocket.ComponentData.Load.MagSaveData>();
                        }
                        return this.magSaveData;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                            "magazineKey",
                            "munitionKey",
                            "quantity"
                    })
                    public static class MagSaveData {

                        @XmlElement(name = "MagazineKey", required = true)
                        protected String magazineKey;
                        @XmlElement(name = "MunitionKey", required = true)
                        protected String munitionKey;
                        @XmlElement(name = "Quantity")
                        protected short quantity;

                        /**
                         * Gets the value of the magazineKey property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getMagazineKey() {
                            return magazineKey;
                        }

                        /**
                         * Sets the value of the magazineKey property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setMagazineKey(String value) {
                            this.magazineKey = value;
                        }

                        /**
                         * Gets the value of the munitionKey property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getMunitionKey() {
                            return munitionKey;
                        }

                        /**
                         * Sets the value of the munitionKey property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setMunitionKey(String value) {
                            this.munitionKey = value;
                        }

                        /**
                         * Gets the value of the quantity property.
                         *
                         */
                        public short getQuantity() {
                            return quantity;
                        }

                        /**
                         * Sets the value of the quantity property.
                         *
                         */
                        public void setQuantity(short value) {
                            this.quantity = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="MagSaveData" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "magSaveData"
                })
                public static class MissileLoad {

                    @XmlElement(name = "MagSaveData")
                    protected List<SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData> magSaveData;

                    /**
                     * Gets the value of the magSaveData property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the magSaveData property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getMagSaveData().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData }
                     *
                     *
                     */
                    public List<SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData> getMagSaveData() {
                        if (magSaveData == null) {
                            magSaveData = new ArrayList<SerializedShip.SocketMap.HullSocket.ComponentData.MissileLoad.MagSaveData>();
                        }
                        return this.magSaveData;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="MagazineKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="MunitionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                            "magazineKey",
                            "munitionKey",
                            "quantity"
                    })
                    public static class MagSaveData {

                        @XmlElement(name = "MagazineKey", required = true)
                        protected String magazineKey;
                        @XmlElement(name = "MunitionKey", required = true)
                        protected String munitionKey;
                        @XmlElement(name = "Quantity")
                        protected byte quantity;

                        /**
                         * Gets the value of the magazineKey property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getMagazineKey() {
                            return magazineKey;
                        }

                        /**
                         * Sets the value of the magazineKey property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setMagazineKey(String value) {
                            this.magazineKey = value;
                        }

                        /**
                         * Gets the value of the munitionKey property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getMunitionKey() {
                            return munitionKey;
                        }

                        /**
                         * Sets the value of the munitionKey property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setMunitionKey(String value) {
                            this.munitionKey = value;
                        }

                        /**
                         * Gets the value of the quantity property.
                         *
                         */
                        public byte getQuantity() {
                            return quantity;
                        }

                        /**
                         * Sets the value of the quantity property.
                         *
                         */
                        public void setQuantity(byte value) {
                            this.quantity = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="WepGroup">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MemberKeys">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "wepGroup"
    })
    public static class WeaponGroups {

        @XmlElement(name = "WepGroup", required = true)
        protected SerializedShip.WeaponGroups.WepGroup wepGroup;

        /**
         * Gets the value of the wepGroup property.
         *
         * @return
         *     possible object is
         *     {@link SerializedShip.WeaponGroups.WepGroup }
         *
         */
        public SerializedShip.WeaponGroups.WepGroup getWepGroup() {
            return wepGroup;
        }

        /**
         * Sets the value of the wepGroup property.
         *
         * @param value
         *     allowed object is
         *     {@link SerializedShip.WeaponGroups.WepGroup }
         *
         */
        public void setWepGroup(SerializedShip.WeaponGroups.WepGroup value) {
            this.wepGroup = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MemberKeys">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "memberKeys"
        })
        public static class WepGroup {

            @XmlElement(name = "MemberKeys", required = true)
            protected SerializedShip.WeaponGroups.WepGroup.MemberKeys memberKeys;
            @XmlAttribute(name = "Name")
            protected String name;

            /**
             * Gets the value of the memberKeys property.
             *
             * @return
             *     possible object is
             *     {@link SerializedShip.WeaponGroups.WepGroup.MemberKeys }
             *
             */
            public SerializedShip.WeaponGroups.WepGroup.MemberKeys getMemberKeys() {
                return memberKeys;
            }

            /**
             * Sets the value of the memberKeys property.
             *
             * @param value
             *     allowed object is
             *     {@link SerializedShip.WeaponGroups.WepGroup.MemberKeys }
             *
             */
            public void setMemberKeys(SerializedShip.WeaponGroups.WepGroup.MemberKeys value) {
                this.memberKeys = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "string"
            })
            public static class MemberKeys {

                protected List<String> string;

                /**
                 * Gets the value of the string property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the string property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getString().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 *
                 *
                 */
                public List<String> getString() {
                    if (string == null) {
                        string = new ArrayList<String>();
                    }
                    return this.string;
                }

            }

        }

    }

}
